version: '3'


services:
  redis:
    image: redis/redis-stack-server:7.0.6-RC8
    ports:
      - "6379:6379"
  webapp:
    # See https://aka.ms/vscode-remote/containers/non-root for details.
    user: node
    build: 
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        VARIANT: 18-bullseye
    volumes:
      - ..:/workspaces/terraguard-ui:cached
      - node_modules:/workspaces/terraguard-ui/node_modules
      #- $HOME/.ssh/:/home/vscode/.ssh/ # Mount the ssh folder to authenticate with github
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

volumes:
  node_modules:
